services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: dist  # Asegúrate de que este es el directorio correcto donde se encuentra tu build
    routes:
      - type: rewrite
        source: /<*>  # Redirige todas las rutas
        destination: /index.html  # A tu archivo de entrada
